# Generated by Django 6.0.1 on 2026-01-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_type',
            field=models.CharField(choices=[('internal', 'Internal Student'), ('external', 'External Student')], default='internal', max_length=20),
        ),
    ]
